#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ] || [ "$branch" = "develop" ]; then
  echo "You cannot commit directly to $branch branch! Please raise a PR instead."
  exit 1
fi
